#ifndef _STATICMESHLIST_H
#define _STATICMESHLIST_H

// Modified by TP (to add new shapes for new physics models)

enum EStaticMeshList
{
	STATICMESH_NULL,
	STATICMESH_SKULL,
	STATICMESH_SPHERE,
	STATICMESH_SPHERE1,
	STATICMESH_SPHERE2,
	STATICMESH_SPHERE3,
	STATICMESH_CUBE,
	STATICMESH_SOLDIER,
	STATICMESH_SMALLMARBLE,
	STATICMESH_MEDIUMMARBLE,
	STATICMESH_LARGEMARBLE,
	STATICMESH_CYLINDER,
	STATICMESH_PLANE,
	STATICMESH_CAPSULE
};

#endif