#ifndef _TEXTURELIST_H
#define _TEXTURELIST_H

enum ETexture
{
	TEXTURE_NULL,
	TEXTURE_WHITE,
	TEXTURE_BUTTON_RED,
	TEXTURE_BUTTON_RED2,
	TEXTURE_BUTTON_RED3,
	TEXTURE_RECTANGLE,
	TEXTURE_RIGHT_NOTCLICKED,
	TEXTURE_RIGHT_OVER,
	TEXTURE_RIGHT_CLICKED,
	TEXTURE_LEFT_NOTCLICKED,
	TEXTURE_LEFT_OVER,
	TEXTURE_LEFT_CLICKED,
	TEXTURE_SPLAYER,
	TEXTURE_SPLAYER_CLICKED,
	TEXTURE_SPLAYER_OVER,
	TEXTURE_BACKGROUND1,
	TEXTURE_POWERBARFRONT,
	TEXTURE_POWERBARBACK,
	TEXTURE_POWERBAR,
	TEXTURE_HOST,
	TEXTURE_HOSTOVER,
	TEXTURE_JOIN,
	TEXTURE_JOINOVER
};

#endif